name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs'
      - README.md
  pull_request:

jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: java -version
      - run: cp src/tools/upx /usr/local/bin
      - name: Build
        run: ./mvnw clean package -DskipTests -Pnative
